AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: cicd-data-s3
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3fullaccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 'arn:aws:s3:::*'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: cicd-data-s3
      Path: /
      Roles:
        - !Ref S3Role

Outputs:
  S3RoleDetails:
    Description: cicd s3 role info
    Value: !Ref InstanceProfile
    Export: 
      Name: cicds3role-S3RoleProfileName